# file: ansible-role-barman/tasks/install.yml

- name: Ensure PostgreSQL yum repo is installed
  yum:
    name: "{{ barman_postgresql_yum_repo }}"
    state: present

- name: Add PostgreSQL repository
  yum_repository:
    name: postgres-{{ barman_postgres_version }}
    description: "2ndQuadrant packages (PG{{ barman_postgres_version }}) for {{ ansible_distribution_major_version }} - {{ ansible_machine }}"
    baseurl: https://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/{{ ansible_machine }}/

- name: Make sure the dependencies are installed
  yum:
    name: "{{ barman_yum_packages }}"
    state: present

- name: Install PostgreSQL Client
  yum:
    name: "postgresql12"
    state: present

- name: Install Barman
  yum:
    name: "barman"
    state: present
  when: not barman_client_only

- name: Install Barman CLI
  yum:
    name: "barman-cli"
    state: present
  when: barman_client_only

- name: Install pip packages
  pip:
    name: "{{ barman_pip_packages }}"
